### ISSUE TITLE
Status icons should be more intelligent

### ISSUE THREAD

**Issue by chriskuehl** [ocf/ocfweb#1]
Currently they are just constant `True`, which is only ok for the "web" one.

We can change them by pushing the site, but ideally they'd do something smart (even pinging the relevant server would be OK).

It would be cool if they read a file in `~staff` so that we could update the status immediately.

**Comment by matthew-mcallister** [comment]
I don't see the status icons as being very useful. Those services will be up virtually all the time. When one goes down, it's a big deal and will get posted about in the status blog.

**Comment by chriskuehl** [comment]
It might be more useful to remove them and replace it with some kind of alert system when things are actually down. The main reason I added them is that it's been a common request from the pubstaff to have alerts when printing or such is down.
