### ISSUE TITLE
Move servers page out of docs, into a real page

### ISSUE THREAD

**Issue by chriskuehl** [ocf/ocfweb#10]
It really never should have been part of the wiki anyway. It's totally broken now.

https://dev.ocf.berkeley.edu/docs/servers/

![](http://i.fluffy.cc/73bHt35wQ8tNWc6nNB8Q3H9ltKW8sJ23.png)

**Comment by matthew-mcallister** [comment]
Still need to know where to link to it, but it's working now.

**Comment by chriskuehl** [comment]
I think it probably belongs under /docs/staff/ but moving it there currently is a bit tricky. I have a branch which makes it easier. You can just push what you have now if you'd like.
