### ISSUE TITLE
Make account section look and feel better

### ISSUE THREAD

**Issue by chriskuehl** [ocf/ocfweb#107]
Right now there are lots of issues, let's try to list them here.

**Comment by matthew-mcallister** [comment]
![password page](http://i.fluffy.cc/VCwcb2xprPZq9nvVR9CTDVNRp8XGCjPH.png)

For starters,

* There's no vertical separation between the page content and header
* Buttons have default look and feel which doesn't match with the rest of the site
* Pages have no titles (the green bar would make it look better too)
* Pages are very empty; I suggest additional padding on the left and bigger text fields

**Comment by chriskuehl** [comment]
this is done
