### ISSUE TITLE
Reevaluate "unofficial" web hosting domains

### ISSUE THREAD

**Issue by daradib** [ocf/ocfweb#109]
We should reevaluate the "unofficial" web hosting domains (ocf.sexy and open.cf) documented on the web hosting page. I had listed them as unofficial in case we later decided to stop supporting them. I suggest we either make sure to renew them or remove them from docs.

Currently, open.cf is registered to us but DNS not resolve and the registration expires in March. If we don't renew, a squatter/spammer may take over.

Does anyone use these domains? Is the ~~cool factor~~ branding or possible future use valuable?

**Comment by chriskuehl** [comment]
my thoughts:

* keep ocf.io, obviously. i don't think anyone disagrees here, we use it extensively.
* drop open.cf, the registrar is kind of sketchy
* i'm -0 for keeping ocf.sexy (imo we should stop advertising it and let it expire, but I don't feel strongly about it and wouldn't object if someone wants to keep it)
* save up $100k and buy the `ocf` tld from icann?

**Comment by matthew-mcallister** [comment]
> save up $100k and buy the ocf tld from icann?

And do what with it? Move to `ocf.ocf.ocf`?

**Comment by chriskuehl** [comment]
let's move this to the bod rt queue instead
