### ISSUE TITLE
about needs new lab photos

### ISSUE THREAD

**Issue by chriskuehl** [ocf/ocfweb#115]
https://static.ocf.berkeley.edu/img/about/server-lab.png

on this page: https://www.ocf.berkeley.edu/about/staff

the current is outdated:
![](http://i.fluffy.cc/P0FQ9mzdTpGv5Tlf7pSLMdfZ34SH7P2g.png)

**Comment by chriskuehl** [comment]
http://i.fluffy.cc/JqnDVcq6bfB4HkhZctB7FrP8KTHPw5ZR.jpg

someone should also take a good server room one (probably showing more than just the server rack)

**Comment by chriskuehl** [comment]
peter's server room photo
http://i.fluffy.cc/H3gCqwjVjlg4NjZR4khMBKpbkg7gNDSK.jpg

**Comment by chriskuehl** [comment]
@hexecute why is it so blurry?

**Comment by jvperrin** [comment]
I took a few photos, I couldn't get much of the room apart from the server rack unfortunately though, since it is placed close to the wall.

http://i.fluffy.cc/xgnwT43MxJk74tfZ0CG6nD1sBs9RhnvC.zip

**Comment by redplanks** [comment]
Bump: I believe someone took a photo of the lab post-cleaning?

**Comment by nikhiljha** [comment]
This was fixed at some point...

![](https://static.ocf.berkeley.edu/img/about/171-mlk-lab.jpg)

**Comment by jvperrin** [comment]
Fixed by #498
