### ISSUE TITLE
Merge atool into ocfweb

### ISSUE THREAD

**Issue by chriskuehl** [ocf/ocfweb#13]
This is a long-term goal and will take some work. Actually merging the code should be straightforward. The main concerns are deployment:

* Need to add login somehow to ocfweb (not hard, just needs some thought; we want to handle both logging in with CalNet, and logging in with an OCF account)
* Need to ensure we treat cookies carefully
  * invalidating sessions on privilege change to avoid session fixation -- which atool doesn't do currently
  * ensure cookies don't get passed to user sites

It would be cool if it could use GSSAPI for users in the lab (and e.g. feature their print quota on the home page).

**Comment by chriskuehl** [comment]
@jvperrin @matthew-mcallister how is this going? Do you need any help?

**Comment by jvperrin** [comment]
I'm not currently working on it actually, since @matthew-mcallister is further along than I am and I didn't want to duplicate what he was doing. However, if I can help him with merging or do any refactoring once it is merged then I'd be happy to help.

**Comment by chriskuehl** [comment]
We should make sure we're on the same page. I'm not really working on this but will be happy to lend assistance / do code review.

It's my understanding that the plan right now is basically:

1. **Phase one.** @matthew-mcallister merges atool code into ocfweb and fixes it up (basically the bare minimum work necessary to get it functioning), it becomes available at `/accounts/` or similar. We deploy it into production and test it, but no links are changed (we still use atool). Users would be able to use the functionality, but only if they go to the URL directly.
2. **Phase two.** We figure out how to avoid passing cookies to user websites, and then we kill atool in prod and replace it with this.
3. **Phase three.** Design a better login system for ocfweb as a whole, refactor things, improve UX, etc.

Does that sound kinda reasonable?

**Comment by jvperrin** [comment]
Yeah, sounds good to me. Is avoiding passing cookies to user websites as easy as simply assigning the cookie only to the `www` subdomain, or is it more complicated than that?

**Comment by chriskuehl** [comment]
@jvperrin no, it's more complicated because user websites are on the `www` subdomain. The attack we're concerned about is that an authenticated user visits `www.ocf.b.e/~ckuehl/` and my code can read the user's token.

Right now atool sets cookies for `accounts.ocf.b.e` which `www.ocf.b.e/~ckuehl/` can't read. But once atool is on `www` anyone will be able to read them.

The only way I can think to fix this is to have Apache rewrite the Cookie header before passing to user sites, but I'm not sure if this is easy (it needs to do so intelligently). We still need to investigate a little how to best approach that. If the hackery needed to avoid it is too much, then we can resort to deploying authenticated portions of ocfweb on a separate subdomain (but same instance), but it'd be cool to avoid that (would allow e.g. the home page to show useful info when you're logged in).

We also need to be concerned about a session fixation attack, which we're currently vulnerable to. Any OCF user (or even any other `berkeley.edu` site, like `cs.berkeley.edu`) can retrieve a valid session cookie from atool/ocfweb and then trick the victim's browser into setting it on a parent domain (e.g. `berkeley.edu`). The victim then logs into atool and the session is now a session for an authenticated user. Since the attacker knows the cookie, they're now logged in. atool is vulnerable to this right now.

The proper fix is to invalidate sessions (and issue a new token) on privilege change.

**Comment by jvperrin** [comment]
Oh, good point, I forgot about those, I guess I was only thinking of subdomains. I also thought that the cookie `path` attribute might fix things, but then we wouldn't be able to display any user information on the home page since it's the root path, so that doesn't really help.

Would rewriting the Cookie header for user sites break any user sites that currently use cookies? I'm not sure if there are any that actually do... Looking at [`SessionCookieRemove`](https://httpd.apache.org/docs/2.4/mod/mod_session_cookie.html#SessionCookieRemove), it looks promising for our use, but it appears to discard all cookies, not just the session ones, which might break user sites if they use cookies for anything.

**Comment by chriskuehl** [comment]
SessionCookieRemove looks like it's for some kind of Apache-based sessions that we don't use (and I've never heard of). We don't have that module enabled.

We would need to strip cookies intelligently, e.g. removing all cookies that start with `OCFWEB_` or something. If we just blindly strip the `Cookie` header we'll break users' sites.

The header is like `Cookie: a=b; c=d; e=f;` so we'd actually have to rewrite it, not just drop the header line.

**Comment by chriskuehl** [comment]
Something like this using `mod_headers` seems to work:

    RequestHeader edit* Cookie (;?\s*OCFWEB_.+?)=.+?(;|$) $1=REMOVED$2

I didn't test it super extensively but it seems to redact our cookies without touching others. It's possible to remove the cookies entirely using the regex but might be easier for debugging to not do that.

We'll need to prevent users from overriding this in `.htaccess`.

I'm using this to test: https://gist.github.com/anonymous/f24c09e76bb15066e463 https://www.ocf.berkeley.edu/~ckuehl/tmp/cookies/

**Comment by jvperrin** [comment]
Looks good to me and my limited Apache knowledge, I didn't even know this was possible! :+1:

**Comment by nattofriends** [comment]
Wouldn't such a page still be able to read the actual cookie value by JS
and send it back by other means?

**Comment by chriskuehl** [comment]
@nattofriends not if you set it as an HTTP-only cookie

https://www.owasp.org/index.php/HttpOnly

**Comment by nattofriends** [comment]
Fair enough, but I saw no discussion of that.

2015-12-04 3:18 GMT-08:00 Chris Kuehl <notifications@github.com>:

**Comment by matthew-mcallister** [comment]
@chriskuehl That's the plan as it seemed to me. I actually merged all the code on Monday, I just haven't been able to test it. I think the only issue is how to reach ocfweb on the test server (meltdown) from another machine.

**Comment by chriskuehl** [comment]
@matthew-mcallister if you want to test in a prod-like environment, you can `dpkg -i` it onto your dev machine.

You'll need to forward the port via SSH (8080 I think?) and fake the Host header (e.g. `curl -H 'Host: www.ocf.berkeley.edu'`, or use a browser extension).

**Comment by matthew-mcallister** [comment]
Oops, I thought spoofing the header wasn't working, but I was actually getting an ocfweb error. Will post an update when phase 1 is done.

**Comment by chriskuehl** [comment]
Also, I wouldn't worry about styling or anything like that for phase 1. Once we have the bare minimum merged, we can split up that work.

**Comment by chriskuehl** [comment]
The cookie filtering should be working, and sessions are working on prod. You can try at https://www.ocf.berkeley.edu/test/session

You can see that the PID of the worker process processing your request changes as you refresh, but you keep the same session (they're in Redis).

I'll try to get account creation and other things working tomorrow... there are some missing files.

**Comment by chriskuehl** [comment]
this is done!
