### ISSUE TITLE
Document server migration

### ISSUE THREAD

**Issue by matthew-mcallister** [ocf/ocfweb#140]
Supposedly there's a script for copying VMs between physical machines.

**Comment by jvperrin** [comment]
Here's the script, it's pretty well commented: https://github.com/ocf/utils/blob/master/staff/sys/migrate-vm

**Comment by chriskuehl** [comment]
Step 6 in those comments is actually a lie, but it should probably do that.

**Comment by matthew-mcallister** [comment]
Yeah, I've looked at it. It still would be worth having a page or section documenting the script, however.
