### ISSUE TITLE
Needs Google Analytics

### ISSUE THREAD

**Issue by chriskuehl** [ocf/ocfweb#17]

**Comment by nattofriends** [comment]
[dara intensifies]

2015-08-31 22:01 GMT-07:00 Chris Kuehl <notifications@github.com>:

**Comment by chriskuehl** [comment]
This was a response to @daradib reminding me I forgot to add it. "I like the absence of Google Analytics (though arguably Google is still collecting analytics from the map)."

**Comment by daradib** [comment]
I need to learn to keep quiet.

**Comment by chriskuehl** [comment]
fixed by 59fc0c159a3beffd857602df7283eafdac2b053f
