### ISSUE TITLE
favicon is pretty blurry

### ISSUE THREAD

**Issue by chriskuehl** [ocf/ocfweb#18]
I made it from the SVG directly (i.e. not resizing a raster), so not sure why. Probably needs some pixel love.

**Comment by nikhiljha** [comment]
Looks like this was fixed somewhere along the line- closing.

https://github.com/ocf/ocfweb/blob/aa12feca634f7f32f422890f1642fbe82580d1df/ocfweb/templates/partials/head.html#L35
