### ISSUE TITLE
staff hours page is kinda slow

### ISSUE THREAD

**Issue by chriskuehl** [ocf/ocfweb#183]
slow enough that i noticed it, anyway. should be easy to add some caching to whatever is slow.

`time curl https://www.ocf.berkeley.edu/staff-hours` takes ~600ms

by comparison, home page is ~300ms and `/docs/` is ~100ms

**Comment by chriskuehl** [comment]
much faster now, ~125ms

as a side effect, the home page is also now down to ~180ms

**Comment by matthew-mcallister** [comment]
Nice catch and fix. ocflib will already error if a nonexistent username shows up in the staff hours anyways.
