### ISSUE TITLE
Display recent update(s) from status blog

### ISSUE THREAD

**Issue by matthew-mcallister** [ocf/ocfweb#19]
This may or may not be tricky, but even getting only the headlines from the status blog would be really valuable. We want everyone to be well aware what's happening when there's a security alert or a service goes down.

**Comment by nattofriends** [comment]
Just kill #1 and replace with this if last post updated date <= N days, N =
3.

2015-09-04 15:48 GMT-07:00 Matthew McAllister <notifications@github.com>:

**Comment by chriskuehl** [comment]
who wants to [parse xml](http://status.ocf.berkeley.edu/feeds/posts/default)

**Comment by chriskuehl** [comment]
I think we could drop #15 if we do this

**Comment by nattofriends** [comment]
Throw xpath at the problem

[install lxml]

>>> from lxml import etree
>>> tree = etree.parse("http://status.ocf.berkeley.edu/feeds/posts/default")
>>> tree.xpath("//atom:entry[1]/atom:title", namespaces={'atom': '
http://www.w3.org/2005/Atom'})[0].text
'Removing automatic redirects from www.ocf.b.e/user -> www.ocf.b.e/~user'

2015-09-04 18:47 GMT-07:00 Chris Kuehl <notifications@github.com>:

**Comment by chriskuehl** [comment]
amazing

**Comment by chriskuehl** [comment]
added parsing in 409a0caca4ea2769aa565a51a87cfdea32184931, need to figure out how we want to display it

**Comment by chriskuehl** [comment]
ok, I think I finally found a decent way to display this:

![](http://i.fluffy.cc/8LgqGtJtQJGv9st6mZKMhbKQkStLlHHp.png)

I'm pushing now and closing this issue, but comments are welcome.

**Comment by chriskuehl** [comment]
b70c37fdd1b16c420e91dbfe6623ffcecf2f3861

**Comment by kpengboy** [comment]
Maybe don't display messages older than a certain age (e.g. 1 month)? In the screenshot posted for example, the fact that there was downtime 1 month ago is not terribly useful.

**Comment by chriskuehl** [comment]
that was intentional; originally it did, but it wasn't very useful and looked funky.
