### ISSUE TITLE
figure out how better to handle unpinned ocflib

### ISSUE THREAD

**Issue by chriskuehl** [ocf/ocfweb#192]
Currently we use `--no-cache` when building all the Docker images, which is really really slow.

The reason is that otherwise the image gets cached up to (and including) this line: https://github.com/ocf/ocfweb/blob/c0bf5228accb7a7b5bbc963426213b944dd3fbb9/Dockerfile#L32-L35

We should probably do something like install everything besides ocflib in that layer, then install the latest ocflib in the next layer (which we always run via some Docker cache-busting trick).

The slow part is installing all the system packages at the start, and then all the Python packages later on. Installing ocflib and everything else is very fast. So if we can cache everything up until then, builds will normally take only seconds instead of the minutes they take now.

**Comment by matthew-mcallister** [comment]
How about on the next line
```dockerfile
RUN /opt/ocfweb/venv/bin/pip install ocflib
```
pip will uninstall the old cached version and replace it with the most recent.

**Comment by chriskuehl** [comment]
The problem is that docker will just cache that line and we'll never get a newer version of ocflib unless one of the previous layers change. That's why I mentioned we'd need some trick to always break that cache on the line before that.

**Comment by matthew-mcallister** [comment]
Oh, I thought you meant we already _had_ a cache-busting technique.

According to [the Dockerfile reference](https://docs.docker.com/engine/reference/builder/), the proper way to invalidate the cache is with `ADD`:

> The first encountered ADD instruction will invalidate the cache for all following instructions from the Dockerfile if the contents of <src> have changed. This includes invalidating the cache for RUN instructions. See the [Dockerfile Best Practices](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#build-cache) guide for more information.

I.e. generate a file containing a timestamp or commit hash and ADD it.

**Comment by chriskuehl** [comment]
yeah, i think your edit is on-point. just need to figure out how to get the latest ocflib version from pypi
