### ISSUE TITLE
Have next 7 days in hours sidebar

### ISSUE THREAD

**Issue by matthew-mcallister** [ocf/ocfweb#20]
This means all our normal hours are visible on a normal week.

**Comment by chriskuehl** [comment]
The reasoning behind not just showing a full week is that it's really the *next* 4 days (currently, anyway) and takes into account holidays and such. If it just showed Sunday through Saturday it would be less intuitive what's happening ("It's Christmas every Tuesday?").

If we show the next 7 and make it clear that's what it is, it's probably ok.

**Comment by chriskuehl** [comment]
Tagging this as blocking and self-owning since I already started it but didn't finish and it looks even worse right now.

![](http://i.fluffy.cc/N6h7KZwgZLznDq8rrkM0JBcGQQkRBtnX.png)
