### ISSUE TITLE
New builds of ocf/dockers should trigger ocfweb builds of master

### ISSUE THREAD

**Issue by chriskuehl** [ocf/ocfweb#214]
similar to how builds of ocflib do this

**Comment by jvperrin** [comment]
I can add this, will need to do it with other repos anyway, since lots of things depend on ocf/dockers and currently don't build when it changes. It could lead to a ton of Jenkins jobs and then a mass-redeploy whenever anything is pushed to ocf/dockers, but that hopefully shouldn't be a problem.

**Comment by chriskuehl** [comment]
yeah, i doubt it will be a huge problem, but if it is, we could just cron them at different times in the middle of the night each day regardless of whether ocf/dockers got built

(but it gets built daily too, so it'd mostly do the same thing)

**Comment by chriskuehl** [comment]
done in https://github.com/ocf/ocfweb/pull/251

**Comment by jvperrin** [comment]
Thanks for doing this, I meant to do this a long time ago and forgot about it lol
