### ISSUE TITLE
Minify the JS we serve

### ISSUE THREAD

**Issue by chriskuehl** [ocf/ocfweb#218]
low priority, but would be nice to reduce the size a little

imo we should add a comment at the top with a link to the unminified source, in the spirit of open source

**Comment by kevinmasd** [comment]
Which files? Only JS I see on the website is site.js and minified versions of jQuery, Underscore, and Bootstrap.

**Comment by chriskuehl** [comment]
the one unminified one, site.js

**Comment by chriskuehl** [comment]
i wonder if we really need underscore... we can surely factor out the couple places it's used?

**Comment by chriskuehl** [comment]
there is some other js, though, e.g. the vhost_mail page:
https://github.com/ocf/ocfweb/blob/11aca52d18c8e7865e8943dcf4ec871fa4b051a0/ocfweb/static/js/pages/account/vhost_mail.js

**Comment by kevinmasd** [comment]
Underscore doesn't seemed to be used, as far as I can tell.
https://github.com/ocf/ocfweb/tree/jsminify had a first-pass minification; I'll see if it could get smaller, but these files weren't that large in the first place.

**Comment by chriskuehl** [comment]
A couple comments:

* Can we use uglify instead of Closure? That thing gives me enough headaches at my day job. Don't think it's worth it for us (we won't be able to use advanced mode anyway).
* This should be part of the build process, not something committed in the repo. Look at how the CSS gets generated as an example (we compile scss -> css but don't keep the CSS checked in). There's a few different problems with checking in files like this (e.g. can get out of sync, can't merge two branches that touch JS at all anymore since the entire files will conflict, etc.).

**Comment by chriskuehl** [comment]
I already removed underscore in https://github.com/ocf/ocfweb/commit/11ddcef984a6ee3d8be2f3bb31ea7324a27c3781

**Comment by kevinmasd** [comment]
Issue for Uglifyer is that there is only an old python wrapper for the Javascript app. scss at least had a wrapper. (also make scss isn't an valid command anymore)

**Comment by chriskuehl** [comment]
> also make scss isn't an valid command anymore

it's here:
https://github.com/ocf/ocfweb/blob/11ddcef984a6ee3d8be2f3bb31ea7324a27c3781/Makefile#L62

we don't necessarily need python bindings, we just use them because libsass has well-maintained ones.

i'd probably suggest to use nodeenv to set up a node environment. we already install it (because of pre-commit), so it's easy to do somethingl ike this in the Makefile:

```Makefile
+nenv: venv
       $(BIN)/nodeenv --prebuilt nenv
       . nenv/bin/activate && npm install uglify-js
```

then you'll be able to `. nenv/bin/activate && uglifyjs --help`

(unfortunately the activating is necessary unlike in python, just using it out of the bin directory is insufficient to get all the env vars right with nodeenv)

there's also a reasonably recent uglify version in debian, not against installing that system-wide if it helps
