### ISSUE TITLE
Docs: Merge "Printing" and "Printing policies"

### ISSUE THREAD

**Issue by matthew-mcallister** [ocf/ocfweb#24]
These pages are too short to be separate articles.

**Comment by matthew-mcallister** [comment]
Does the tag seem like a good way to handle wiki "todo" tasks? The rest of the tags are descriptive while this one is more to do with the area of development.

**Comment by chriskuehl** [comment]
yea, I think using github issues for this is fine

**Comment by matthew-mcallister** [comment]
I added a docs tag when I made this issue; don't know where it went, but that's what I was referring to.

**Comment by chriskuehl** [comment]
thanks github

**Comment by chriskuehl** [comment]
done in 55bc8117921476dfb45f6c1c06ade9971abaebac
