### ISSUE TITLE
docs/servers: anchors are too large

### ISSUE THREAD

**Issue by matthew-mcallister** [ocf/ocfweb#240]
@tahabi 

The anchor links added in #234 actually include a rectangle directly above the host name.

![screenshot_2017-02-04_23-46-13](https://cloud.githubusercontent.com/assets/6722367/22624581/2316b63e-eb35-11e6-9a08-bad8162e3187.png)

**Comment by tahabi** [comment]
Yeah, that's the ::before pseudoclass that pushes the anchor down below the navbar so it's visible when you follow the link. AFAIK it doesn't really affect anything else, it's just the result of margin-top. https://github.com/ocf/ocfweb/blob/master/ocfweb/static/scss/pages/docs/_servers.scss#L78
