### ISSUE TITLE
Fix sidebar on staff docs page

### ISSUE THREAD

**Issue by chriskuehl** [ocf/ocfweb#26]
I guess this isn't really blocking launch but we should probably fix the sidebar on the staff docs page...

![](http://i.fluffy.cc/ZzwKsW6WnsHMf30mLzNdrl7nmqQdKN09.png)

**Comment by matthew-mcallister** [comment]
Is it broken or does it just need text?

**Comment by chriskuehl** [comment]
it works fine, just needs text

**Comment by matthew-mcallister** [comment]
I'm still open to adding text to the sidebar, so I'll actually reopen this in case someone comes up with an idea for it.

**Comment by nikhiljha** [comment]
This was fixed at some point too...

https://github.com/ocf/ocfweb/blob/master/ocfweb/docs/templates/docs/index.html#L36-L40
