### ISSUE TITLE
error in print stats

### ISSUE THREAD

**Issue by tahabi** [ocf/ocfweb#261]
papercut has -6 pages on Valentines Day? @shex1627 

![screenshot_2017-02-28_01-17-31](https://cloud.githubusercontent.com/assets/1916822/23399059/b4a06156-fd53-11e6-8c01-ef629a3c5806.png)

**Comment by chriskuehl** [comment]
i've noticed a few more of these issues as well, even with the old printers

e.g. look at https://www.ocf.berkeley.edu/stats/printing/pages-printed

logjam has 1,697,341 on may 26 2016, but 1,697,340 on aug 24 2016

i'm guessing these are the printers giving us bad data somehow? not sure there's anything we can do to fix that data :\

**Comment by tahabi** [comment]
Aren't these numbers coming from the jobs table? IIRC only the CUPS posthook writes to that table right?

**Comment by matthew-mcallister** [comment]
This data comes from the printers, we just log it.

**Comment by chriskuehl** [comment]
This isn't really an ocfweb issue, I think we can close it. Maybe we can re-ticket under ocflib (or just rt todo) if we want to try to find a more accurate way to get pages printed. I have a feeling we might not find anything actionable, though, if the printers are just going to lie to us.
