### ISSUE TITLE
Responsive layout on home page

### ISSUE THREAD

**Issue by chriskuehl** [ocf/ocfweb#3]
There are a couple quirks.

**Comment by chriskuehl** [comment]
I just fixed a few things, some more:

![](http://i.fluffy.cc/SDTzvc9MMmw71KnRPFPHnf1j5ft5Nz8s.png)

![](http://i.fluffy.cc/fjqpjJGg5QNgZLm5R5XZ0gbRpbMwKN5Z.png)

![](http://i.fluffy.cc/fGgzZLx20TZhKS8nQkg8pQ3NjFnrxw0w.png)

![](http://i.fluffy.cc/hDmnQH2wsdfKlqbGnw1213Pm4N6RF2Pl.png)

![](http://i.fluffy.cc/H2KJQJjFp7jGpxl9nnqF69kTLWVWqpFX.png)

![](http://i.fluffy.cc/Xk7R72NH47PKm9Q5kXJ4PhBK918HmMMw.png)

**Comment by nattofriends** [comment]
bome page

2015-09-02 23:48 GMT-07:00 Chris Kuehl <notifications@github.com>:

**Comment by matthew-mcallister** [comment]
Done by @chriskuehl in 8245becb9d0d68ae2f7eec460ca70f03149831c8.
