### ISSUE TITLE
Services - Printing - Technical Details

### ISSUE THREAD

**Issue by hexecute** [ocf/ocfweb#33]
Both links on this [page](https://dev.ocf.berkeley.edu/docs/services/lab/printing/ ) are dead. Are we going to fix them or just delete the links?

[How much toner is left in each printer? (expressed as approximate pages remaining over time)](https://www.ocf.berkeley.edu/~tzhu/printing/oracle/)

[How many pages has each printer printed? (expressed as total pages printed over time)](https://www.ocf.berkeley.edu/~tzhu/printing/history/)

**Comment by chriskuehl** [comment]
They should be replaced with the links at the bottom of the stats page:
http://stats.ocf.berkeley.edu/

**Comment by chriskuehl** [comment]
(I stole the oracle stuff out of @nattofriends' home directory and put it on stats to be more Official)

**Comment by hexecute** [comment]
For some reason, http://stats.ocf.berkeley.edu/printing/historacle/ isn't working for me.

**Comment by jvperrin** [comment]
Same, it's giving me a 500 error.

**Comment by chriskuehl** [comment]
lol

> [Sat Sep 26 00:43:23.224870 2015] [:error] [pid 25352] [client 71.202.180.90:53632] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4177668 bytes) in /opt/stats/labstats/www/printing/historacle/index.php on line 29

quality php @nattofriends

i'll fix it

**Comment by nattofriends** [comment]
deal w/it

**Comment by chriskuehl** [comment]
done in 55bc8117921476dfb45f6c1c06ade9971abaebac

filed rt#3954 for fixing oracle/historacle
