### ISSUE TITLE
Migrate hosted logos page

### ISSUE THREAD

**Issue by chriskuehl** [ocf/ocfweb#35]
Also remove all the hideous logos...

https://www.ocf.berkeley.edu/images/hosted-logos/index.shtml

**Comment by kpengboy** [comment]
How many people are using said hideous logos?

**Comment by chriskuehl** [comment]
hopefully none. but I'm only proposing removing them from the page, not to delete the images.

**Comment by chriskuehl** [comment]
Done by @matthew-mcallister in #51
