### ISSUE TITLE
Move docs table of contents to top on small screens

### ISSUE THREAD

**Issue by matthew-mcallister** [ocf/ocfweb#41]
On small/narrow screens, the OCF sidebar goes to the bottom of the page. It would be a minor improvement to have the docs ToC in an expandable box near the top like Wikipedia.

**Comment by chriskuehl** [comment]
+1. Ideally it would probably start closed.

**Comment by matthew-mcallister** [comment]
Done in db490a45d746c96543826a149512a11c6c64104b.
