### ISSUE TITLE
Lab page should list staff hours and holidays based off of ocflib

### ISSUE THREAD

**Issue by chriskuehl** [ocf/ocfweb#5]
Currently it's just a wiki page:
https://dev.ocf.berkeley.edu/docs/services/lab/

We have good support in ocflib for hours/holidays now (in use on the home page and the status bar), we should use it.

**Comment by matthew-mcallister** [comment]
We should add a full calendar, maybe something like https://github.com/Serhioromano/bootstrap-calendar

**Comment by matthew-mcallister** [comment]
Done by @chriskuehl in https://github.com/ocf/ocfweb/commit/804e864989293e0c1240c3992730b5a858c749f7.

**Comment by chriskuehl** [comment]
@matthew-mcallister i'm still fine with adding a full calendar at some point, so maybe open another issue if you think it's a good idea.

I mostly didn't do it in that commit to save time.

**Comment by matthew-mcallister** [comment]
OK, it should probably go in a new issue either way.
