### ISSUE TITLE
don't allow sorried users to log in to ocfweb

### ISSUE THREAD

**Issue by abizer** [ocf/ocfweb#501]
this is related to #119 and rt#8225

we currently allow sorried users to log into ocfweb because we just check that the user exists and the password matches. We should probably reject login attempts by sorried accounts. It would likely require adding a bit of logic here: https://github.com/ocf/ocfweb/blob/master/ocfweb/login/ocf.py#L40 to check if the account is sorried before continuing to check the password.

**Comment by dkess** [comment]
Marking this as a good first issue. If a newbie wants to work on this, PM a root staffer and we'll give you the password for the sorried test account (`ofc`)
