### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by MCer4294967296** [ocf/ocfweb#506]
https://www.ocf.berkeley.edu/docs/staff/backend/munin/

Two of the links are dead here. 
`https://github.com/ocf/puppet/blob/master/modules/ocf_stats/files/munin/gen-munin-nodes` is simply moved and can be fixed easily.
`https://github.com/ocf/puppet/blob/master/modules/ocf_stats/files/munin/mail-munin-alert` does not exist anymore and now lives as an .erb file. So what should we do with this?

**Comment by dkess** [comment]
Nice catch! For `mail-munin-alert`, that should point to the erb file.
