### ISSUE TITLE
Incorrect number of desktops

### ISSUE THREAD

**Issue by ja5087** [ocf/ocfweb#526]
https://github.com/ocf/ocfweb/blob/91b2f29e17a2c4ed0177ea0146a37302333b0796/ocfweb/docs/templates/docs/lab.html#L11

You may have observed that we do, in fact, have 31 desktops at the OCF.

**Comment by cg505** [comment]
Only 29 are open to the general public. I believe this is correct.

**Comment by dkess** [comment]
We might be at 30 general use + 1 staff-only + 1 opstaff? Since typhoon is new

**Comment by cg505** [comment]
29 general use. typhoon is already accounted for. see #494.

**Comment by ja5087** [comment]
I'll close this then, thanks!
