### ISSUE TITLE
fix histogram on printing page

### ISSUE THREAD

**Issue by cg505** [ocf/ocfweb#552]
The user histogram is broken on ocf.io/stats/printing. The culprit is https://github.com/ocf/ocfweb/blob/ed143b8f1c59e58157780007fe5fd104ee18d944/ocfweb/stats/printing.py#L58
We should use `SEMESTERLY_QUOTA + 5` instead of 105.

**Comment by expedited** [comment]
is this as simple as just updating that hard-coded value? I think I'll grab this one rn
