### ISSUE TITLE
Remove Google Analytics (w/ or w/o replacement)

### ISSUE THREAD

**Issue by nikhiljha** [ocf/ocfweb#593]
Discussion on IRC, starting here https://irclogs.ocf.berkeley.edu/rebuild/2020-04-28#807157

Summary
- We aren't actually looking at the data.
- It might not be the best (privacy-wise) to have google analytics.

**Comment by PotatoParser** [comment]
Further discussion of removing Google Analytics is needed

**Comment by dkess** [comment]
I would say: bring it up at BoD, if no one defends analytics, remove it and don't bother looking into open-source things to replace it with.

**Comment by BernardZhao** [comment]
Noone defended it in BoD, and we voted to have it removed.
