### ISSUE TITLE
Windows SSH instructions

### ISSUE THREAD

**Issue by ArnNag** [ocf/ocfweb#633]
Windows has shipped with OpenSSH enabled by default since [May](https://virtualizationreview.com/articles/2020/05/18/ssh-on-windows.aspx). Does it still make sense to have [separate instructions](https://www.ocf.berkeley.edu/docs/services/shell/#h4_windows) for Windows users to install PuTTY?

**Comment by ethanhs** [comment]
I would suggest we drop the separate instructions. Putty is kinda annoying to use and doesn't work as well as Windows Terminal IME.
