### ISSUE TITLE
Remove BLM banner

### ISSUE THREAD

**Issue by bjb568** [ocf/ocfweb#637]

**Comment by PotatoParser** [comment]
Resolved by #641

**Comment by cg505** [comment]
https://github.com/ocf/ocfweb/commit/e1f17e836ba4968d49c0d02749da6b663f4f312c#diff-4f11034e45d6b300715dbd2f9922b9911aa9f7dfd5520519ff5aa227a17333bbR75-R83 This was never reverted.
