### ISSUE TITLE
Broken link to apt-dater

### ISSUE THREAD

**Issue by evilpegasus** [ocf/ocfweb#652]
The link to information about apt-dater at 

https://www.ocf.berkeley.edu/docs/staff/procedures/installing-updates/

leads to a [404](https://www.ibh.de/apt-dater/).

It looks like the IBH website either removed the page or moved it.

**Comment by ja5087** [comment]
Thanks for the catch. Maybe a better link is https://github.com/DE-IBH/apt-dater in the meanwhile
