### ISSUE TITLE
Add a page about STF

### ISSUE THREAD

**Issue by snarain01** [ocf/ocfweb#671]
With the vote for the renewal of STF coming soon, it would be nice to have a page on our website that talks about the STF and how it supports us. Along with the extra page, creating a banner on our site that encourages people to vote would also help. ncberberi was able to get confirmation that we can advertise voting on STF to students.

For more information on what the STF is: [https://techfund.berkeley.edu/](https://techfund.berkeley.edu/)

Voting will take place during the ASUC elections on April 5-7

**Comment by ja5087** [comment]
Look to https://github.com/ocf/ocfweb/pull/609 for a model of what to work on

**Comment by singingtelegram** [comment]
Currently assigned to @singingtelegram

**Comment by singingtelegram** [comment]
#673 submitted. Please review.
