### ISSUE TITLE
vhost banner html broken

### ISSUE THREAD

**Issue by chriskuehl** [ocf/ocfweb#80]
from @daradib:

On the vhost banner page:
https://www.ocf.berkeley.edu/docs/services/vhost/badges/

The img src is broken for virtual hosts, unless you wish to include /hosted-logos in every vhost definition, which is not necessarily a bad idea.

Also please add a trailing slash to the href.

Much thanks.

**Comment by chriskuehl** [comment]
> which is not necessarily a bad idea.

yes this is

**Comment by matthew-mcallister** [comment]
So are there any websites using the broken markup? If so can we just fix with `sed`?

**Comment by chriskuehl** [comment]
@matthew-mcallister I doubt it, we'd have noticed during review. but we should fix it asap

**Comment by chriskuehl** [comment]
actually we might not have noticed during review since it'd work on an ocf.berkeley.edu site. We should check recently approved vhosts just to be safe.

**Comment by matthew-mcallister** [comment]
Found the only one approved this semester with broken code:

http://financeandentrepreneurship.berkeley.edu/

**Comment by chriskuehl** [comment]
Fixed in https://github.com/ocf/ocfweb/commit/28d124f8834e3d2c2a6a589a1451a0b9f4ab3fca and https://github.com/ocf/puppet/commit/ee9bc0d7bc2ca20c36062020963dce0c44290fec
