### ISSUE TITLE
replace references to hearst gym with MLK

### ISSUE THREAD

**Issue by chriskuehl** [ocf/ocfweb#81]
I can do this tonight if somebody doesn't grab it first.

The Google Map is duplicated and yucky right now because I copy-pasted it to support two locations. We should merge those back into a single location (we won't need to support two locations again in the near future).

**Comment by matthew-mcallister** [comment]
I started on this, but you can do it if you'd like. Some pages with 
directions need to be update. Furthermore, coordinates need to be 
updated in ocflib.

**Comment by chriskuehl** [comment]
don't think there's any coordinates in ocflib? there are a couple strings in puppet that need changing but no rush on those, nobody curls the mail server to figure out where we're located.

**Comment by matthew-mcallister** [comment]
You're right, my bad, but there are strings in ocflib referring to the 
gym. I'll create a parallel issue.

Matthew

**Comment by chriskuehl** [comment]
feel free to push your changes, I'm going to have a long night preparing networking for tomorrow / subnet move so probably won't have time until tomorrow anyway

**Comment by chriskuehl** [comment]
done by mattmcal in #82
