### ISSUE TITLE
Fix anchor tags in docs pages

### ISSUE THREAD

**Issue by chriskuehl** [ocf/ocfweb#9]
https://dev.ocf.berkeley.edu/docs/docs/constitution/

![](http://i.fluffy.cc/0lzctKjbbsXkbC8Zb3vJCVR2JpZxnHXV.png)

**Comment by chriskuehl** [comment]
There doesn't seem to be a good syntax for adding anchors in any Markdown flavor :\

The closest is PHP Markdown Extra: https://michelf.ca/projects/php-markdown/extra/#spe-attr

Does this look like a reasonable syntax? Basically doing...

    ### 4.1.1.1 Date of Elections Meeting    {amended_321_1990}

alternatively something like...

    [[!anchor "amended_321_1990"]]

(similar to the meta syntax we adopted from ikiwiki)

**Comment by nattofriends** [comment]
So you have to extend the markdown parser to support this or...?

**Comment by chriskuehl** [comment]
@nattofriends yes. or enable HTML, which I'd rather not just for this... (plus we can potentially export our constitution from markdown -> PDF or something if we want)

there seems to be no standard Markdown syntax for this :\

We already assign ids to headers like `#h5_412-special-general-meetings` but these are automatic based on the header name and might be easy to accidentally break, hence the desire for manually-named anchors.

**Comment by jvperrin** [comment]
Looks like a Mistune [lexer](https://github.com/lepture/mistune#lexers) would work well for this usage case, since we are essentially just adding a single rule so that anchor tags can be added.

**Comment by chriskuehl** [comment]
Yeah, mistune is pretty easy to extend. I was hoping we could at least find a commonly-used Markdown syntax rather than inventing our own again though, even if we have to extend mistune to support it :(

**Comment by kpengboy** [comment]
Maybe the PHP syntax, since it's short and other people are using it.

My second choice would be something like [[#whatever]].

**Comment by chriskuehl** [comment]
done in 4d27dda606e1222c822cccc1389817b843848c0d
